services:
  # A Docker web service
  - type: web
    name: side-cook-ai
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: uv sync
    startCommand: gunicorn wsgi:wsgi_app -w 1 -k uvicorn.workers.UvicornWorkers

